### ISSUE TITLE
gmetp.pl - two faulty lines

### ISSUE THREAD

**Issue by Thamos** [gatech-genemark/GeneMark-ETP#1]
Hi,

when trying GeneMark-ETP with braker3 I found two problems in  gmetp.pl. I think I solved them for my run, but I'm not sure if maybe they occured only because I did something wrong. Both errors occured while running test3 from braker3.

First error is from gmetp.pl line 1227
`...--out ../data/genome.fasta i          --uppercase 1...`

I got an error saying something along the lines of "there is an 'i' where something else is expected. I just changed this line to 

`...--out ../data/genome.fasta  --uppercase 1...`

and it worked.

Second error was that gmetp.pl wanted to change directory to "rnaseq" at some point, but this folder didn't exist yet. I added the line
`MkDir("$workdir/rnaseq");`
somewhere at the beginning of the script and then it worked.

**Comment by KatharinaHoff** [comment]
You should wait until GeneMark-ETP is available for download at http://topaz.gatech.edu/genemark/license_download.cgi

**Comment by wuyh0328** [comment]
> You should wait until GeneMark-ETP is available for download at http://topaz.gatech.edu/genemark/license_download.cgi

Hello, I didn't find this script when I downloaded the genemark_etp with the above URL, why is there no gmetp pl in this package, may I ask why?
