### ISSUE TITLE
"$workdir/rnaseq" not created if providing bam file

### ISSUE THREAD

**Issue by Thamos** [gatech-genemark/GeneMark-ETP#4]
Hi, just wanted to try the new release, however it crashed very fast.

Error message:  error on chdir to: [...]/GeneMark-ETP/rnaseq

So I checked the code and "MkDir("$workdir/rnaseq");" is only called in "PrepareRNASeq" which in turn is only called if "!$bam".

I fixed this in my file and it's running now. :)

Edit: I just remembered this was already fixed in the old version here: https://github.com/gatech-genemark/GeneMark-ETP/commit/943d8cda7c22519ddcfb3854394f8324b0e749ff - however the fix got lost again I guess.

**Comment by tomasbruna** [comment]
Looks like the newest commit overwrote the fix. I'll fix it again. Thanks for reporting.
