### ISSUE TITLE
Braker3/GeneMark-ETP: file not found: complete.gtf, complete.id, complete_uniq.gtf

### ISSUE THREAD

**Issue by JohnUrban** [gatech-genemark/GeneMark-ETP#5]
Hello,

Thank you for all the great GeneMark tools. I am mainly reporting this issue in case it helps your development, but I'd be grateful for any clarification you can provide.

I gave Braker3 a shot, which uses this tool, but am running into an error at the moment.

I described the issue in detail here:
https://github.com/Gaius-Augustus/BRAKER/issues/577

The consensus seems to be that it is a license issue. I was hoping you could confirm that this is or isn't the case.

If it is a license issue, do you have an estimate of when licenses will become available?

Thanks again.

Best,

John Urban

**Comment by tomasbruna** [comment]
I'm closing this issue as it's getting good treatment at https://github.com/Gaius-Augustus/BRAKER/issues/577
